// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: node.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'node';

export interface StreamRequest {
  chunkHash: string;
  chunk: Uint8Array;
}

export interface StreamResponse {
  success: boolean;
}

export const NODE_PACKAGE_NAME = 'node';

export interface NodeServiceClient {
  streamChunk(request: Observable<StreamRequest>): Observable<StreamResponse>;
}

export interface NodeServiceController {
  streamChunk(
    request: Observable<StreamRequest>,
  ): Promise<StreamResponse> | Observable<StreamResponse> | StreamResponse;
}

export function NodeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('NodeService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = ['streamChunk'];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('NodeService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const NODE_SERVICE_NAME = 'NodeService';
