export const REDIS_CLIENT = 'REDIS_CLIENT';
export const AVAILABLE_NODES_KEY = 'AVAILABLE_NODES';
export const HEARTBEAT_TIMEOUT_SECONDS = 15;

export const HEARTBEAT_SERVICE = '[HEARTBEAT_SERVICE]';
export const NODE = '[NODE]';
export const COORDINATOR_GRPC_CLIENT ='COORDINATOR_GRPC_CLIENT';